// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBS_Sistemi.Web.Data;

#nullable disable

namespace OBS_Sistemi.Web.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20231225112703_iliskilendirmeTamamlandi")]
    partial class iliskilendirmeTamamlandi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Bolum", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenimDili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgretimTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumID");

                    b.ToTable("tb_Bolumler");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Danismanlik", b =>
                {
                    b.Property<int>("DanismanlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanismanlikID"));

                    b.Property<int>("OgrElmID")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.HasKey("DanismanlikID");

                    b.HasIndex("OgrElmID")
                        .IsUnique();

                    b.HasIndex("OgrenciID")
                        .IsUnique();

                    b.ToTable("tb_Danismanlik");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Degerlendirme", b =>
                {
                    b.Property<int>("DegerlendirmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegerlendirmeID"));

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<int>("SinavID")
                        .HasColumnType("int");

                    b.Property<double>("SinavNotu")
                        .HasColumnType("float");

                    b.HasKey("DegerlendirmeID");

                    b.HasIndex("OgrenciID")
                        .IsUnique();

                    b.HasIndex("SinavID")
                        .IsUnique();

                    b.ToTable("tb_Degerlendirme");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAcma", b =>
                {
                    b.Property<int>("DersAcmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersAcmaID"));

                    b.Property<string>("AkademikDonem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AkademikYil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<int>("MufreatID")
                        .HasColumnType("int");

                    b.Property<int>("MufredatID")
                        .HasColumnType("int");

                    b.Property<int>("OgrElmID")
                        .HasColumnType("int");

                    b.HasKey("DersAcmaID");

                    b.HasIndex("MufredatID");

                    b.ToTable("tb_DersAcma");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAlma", b =>
                {
                    b.Property<int>("DersAlmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersAlmaID"));

                    b.Property<int>("DersAcmaID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("int");

                    b.HasKey("DersAlmaID");

                    b.HasIndex("DersAcmaID")
                        .IsUnique();

                    b.ToTable("tb_DersAlma");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersHavuzu", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersDili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersSeviyesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<double>("Kredi")
                        .HasColumnType("float");

                    b.Property<int>("Teorik")
                        .HasColumnType("int");

                    b.Property<int>("Uygulama")
                        .HasColumnType("int");

                    b.HasKey("DersID");

                    b.ToTable("tb_DersHavuzu");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersProgrami", b =>
                {
                    b.Property<int>("DersPrgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersPrgID"));

                    b.Property<int>("DersAcmaID")
                        .HasColumnType("int");

                    b.Property<string>("DersGunu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersSaati")
                        .HasColumnType("int");

                    b.Property<int>("DerslikID")
                        .HasColumnType("int");

                    b.HasKey("DersPrgID");

                    b.HasIndex("DersAcmaID")
                        .IsUnique();

                    b.HasIndex("DerslikID")
                        .IsUnique();

                    b.ToTable("tb_DersProgrami");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Derslik", b =>
                {
                    b.Property<int>("DerslikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DerslikID"));

                    b.Property<string>("DerslikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DerslikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.HasKey("DerslikID");

                    b.ToTable("tb_Derslik");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("tb_Kullanicilar");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Mufredat", b =>
                {
                    b.Property<int>("MufredatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MufredatID"));

                    b.Property<string>("AkademikDonem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AkademikYil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<int>("DersDonemi")
                        .HasColumnType("int");

                    b.Property<int>("DersID")
                        .HasColumnType("int");

                    b.HasKey("MufredatID");

                    b.HasIndex("BolumID")
                        .IsUnique();

                    b.HasIndex("DersID")
                        .IsUnique();

                    b.ToTable("tb_Mufredat");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AyrilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersAlmaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.HasIndex("BolumID");

                    b.HasIndex("DersAlmaID");

                    b.HasIndex("KullaniciID")
                        .IsUnique();

                    b.ToTable("tb_Ogrenciler");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.OgretimElemani", b =>
                {
                    b.Property<int>("OgrElmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrElmID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersAcmaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("KurumSicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrElmID");

                    b.HasIndex("BolumID");

                    b.HasIndex("DersAcmaID");

                    b.HasIndex("KullaniciID")
                        .IsUnique();

                    b.ToTable("tb_OgretimElemani");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Sinav", b =>
                {
                    b.Property<int>("SinavID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavID"));

                    b.Property<int>("DersAcmaID")
                        .HasColumnType("int");

                    b.Property<int>("DerslikID")
                        .HasColumnType("int");

                    b.Property<int>("EtkiOrani")
                        .HasColumnType("int");

                    b.Property<int>("OgrElmID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SinavSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinavID");

                    b.HasIndex("DersAcmaID")
                        .IsUnique();

                    b.HasIndex("DerslikID")
                        .IsUnique();

                    b.HasIndex("OgrElmID")
                        .IsUnique();

                    b.ToTable("tb_Sinav");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Danismanlik", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.OgretimElemani", "OgretimElemani")
                        .WithOne("Danismanlik")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Danismanlik", "OgrElmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Ogrenci", "Ogrenci")
                        .WithOne("Danismanlik")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Danismanlik", "OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Degerlendirme", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.Ogrenci", "Ogrenci")
                        .WithOne("Degerlendirme")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Degerlendirme", "OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Sinav", "Sinav")
                        .WithOne("Degerlendirme")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Degerlendirme", "SinavID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAcma", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.Mufredat", "Mufredat")
                        .WithMany()
                        .HasForeignKey("MufredatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mufredat");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAlma", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.DersAcma", "DersAcma")
                        .WithOne("DersAlma")
                        .HasForeignKey("OBS_Sistemi.Web.Models.DersAlma", "DersAcmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersAcma");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersProgrami", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.DersAcma", "DersAcma")
                        .WithOne("DersProgrami")
                        .HasForeignKey("OBS_Sistemi.Web.Models.DersProgrami", "DersAcmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Derslik", "Derslik")
                        .WithOne("DersProgrami")
                        .HasForeignKey("OBS_Sistemi.Web.Models.DersProgrami", "DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersAcma");

                    b.Navigation("Derslik");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Mufredat", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.Bolum", "Bolum")
                        .WithOne("Mufredat")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Mufredat", "BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.DersHavuzu", "DersHavuzu")
                        .WithOne("Mufredat")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Mufredat", "DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("DersHavuzu");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Ogrenci", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.DersAlma", "DersAlma")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("DersAlmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Kullanici", "Kullanici")
                        .WithOne("Ogrenci")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Ogrenci", "KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("DersAlma");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.OgretimElemani", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.Bolum", "Bolum")
                        .WithMany("OgretimElemanlari")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.DersAcma", "DersAcma")
                        .WithMany("OgretimElemanlari")
                        .HasForeignKey("DersAcmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Kullanici", "Kullanici")
                        .WithOne("OgretimElemani")
                        .HasForeignKey("OBS_Sistemi.Web.Models.OgretimElemani", "KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("DersAcma");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Sinav", b =>
                {
                    b.HasOne("OBS_Sistemi.Web.Models.DersAcma", "DersAcma")
                        .WithOne("Sinav")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Sinav", "DersAcmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.Derslik", "Derslik")
                        .WithOne("Sinav")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Sinav", "DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Sistemi.Web.Models.OgretimElemani", "OgretimElemani")
                        .WithOne("Sinav")
                        .HasForeignKey("OBS_Sistemi.Web.Models.Sinav", "OgrElmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersAcma");

                    b.Navigation("Derslik");

                    b.Navigation("OgretimElemani");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Bolum", b =>
                {
                    b.Navigation("Mufredat")
                        .IsRequired();

                    b.Navigation("Ogrenciler");

                    b.Navigation("OgretimElemanlari");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAcma", b =>
                {
                    b.Navigation("DersAlma")
                        .IsRequired();

                    b.Navigation("DersProgrami")
                        .IsRequired();

                    b.Navigation("OgretimElemanlari");

                    b.Navigation("Sinav")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersAlma", b =>
                {
                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.DersHavuzu", b =>
                {
                    b.Navigation("Mufredat")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Derslik", b =>
                {
                    b.Navigation("DersProgrami")
                        .IsRequired();

                    b.Navigation("Sinav")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Kullanici", b =>
                {
                    b.Navigation("Ogrenci")
                        .IsRequired();

                    b.Navigation("OgretimElemani")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Ogrenci", b =>
                {
                    b.Navigation("Danismanlik")
                        .IsRequired();

                    b.Navigation("Degerlendirme")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.OgretimElemani", b =>
                {
                    b.Navigation("Danismanlik")
                        .IsRequired();

                    b.Navigation("Sinav")
                        .IsRequired();
                });

            modelBuilder.Entity("OBS_Sistemi.Web.Models.Sinav", b =>
                {
                    b.Navigation("Degerlendirme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
